import os

ATLAS_CLUSTER_USERNAME= os.environ.get('ATLAS_CLUSTER_USERNAME')
ATLAS_CLUSTER_PASSWORD= os.environ.get('ATLAS_CLUSTER_PASSWORD')
DATABASE_NAME = os.environ.get('DATABASE_NAME')
USER_COLLECTION_NAME= os.environ.get('USER_COLLECTION_NAME')
EMBEDDING_COLLECTION_NAME= os.environ.get('EMBEDDING_COLLECTION_NAME')


